
enum acpm_dvfs_id {
	MIF = ACPM_VCLK_TYPE,
	INT,
	CPUCL0,
	CPUCL1,
	G3D,
	AUD,
	CAM,
	DISP,
	CP,
};

struct vclk acpm_vclk_list[] = {
	CMUCAL_ACPM_VCLK2(MIF, NULL, NULL, NULL, NULL, MARGIN_MIF),
	CMUCAL_ACPM_VCLK2(INT, NULL, NULL, NULL, NULL, MARGIN_INT),
	CMUCAL_ACPM_VCLK2(CPUCL0, NULL, NULL, NULL, NULL, MARGIN_LIT),
	CMUCAL_ACPM_VCLK2(CPUCL1, NULL, NULL, NULL, NULL, MARGIN_BIG),
	CMUCAL_ACPM_VCLK2(G3D, NULL, NULL, NULL, NULL, MARGIN_G3D),
	CMUCAL_ACPM_VCLK2(AUD, NULL, NULL, NULL, NULL, MARGIN_AUD),
	CMUCAL_ACPM_VCLK2(CAM, NULL, NULL, NULL, NULL, MARGIN_CAM),
	CMUCAL_ACPM_VCLK2(DISP, NULL, NULL, NULL, NULL, MARGIN_DISP),
	CMUCAL_ACPM_VCLK2(CP, NULL, NULL, NULL, NULL, MARGIN_CP),
};

unsigned int acpm_vclk_size = ARRAY_SIZE(acpm_vclk_list);
